### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by RUNFUNRUN** [nomadics9/NixOS-Flake#1]
Hi.
I am new to NixOS.
I got this eeror when I ran `install.sh`

```
warning: Git tree '/home/runfunrun/NixOS-Flake' is dirty
building the system configuration...
warning: Git tree '/home/runfunrun/NixOS-Flake' is dirty
Directory "/boot/efi" is not the root of the file system.
systemd-boot not installed in ESP.
No default/fallback boot loader installed in ESP.
Traceback (most recent call last):
  File "/nix/store/ar3wfjim9z6y16jpc5v8qrvxzmkgklfi-systemd-boot", line 341, in <module>
    main()
  File "/nix/store/ar3wfjim9z6y16jpc5v8qrvxzmkgklfi-systemd-boot", line 271, in main
    raise Exception("could not find any previously installed systemd-boot")
Exception: could not find any previously installed systemd-boot
warning: error(s) occurred while switching to the new configuration
```

I searched on the net but could not figure it out.
If you know how to solve this problem, please let me know. I'm using Gnome.

**Comment by nomadics9** [comment]
did you install default nixos with gnome GUI? if so did you change your bootloader to grub?

or your boot folder might be in different path. by default it should be in /boot. if not change line 31 in configuration.nix to the proper path.
`boot.loader.efi.efiSysMountPoint = "/boot/efi";`
 save and run the installer again.

**Comment by RUNFUNRUN** [comment]
Yes.
I did the install with a summary like this

![20230619_000238.jpg](https://github.com/nomadics9/NixOS-Flake/assets/90281553/670be116-06d2-46a4-981e-9f92033acf26)


When I moved to the `/boot` directory, it looked like this.
I've also tried changing it to upper case, like `/boot/EFI`, with the same result.

![20230619_002829.jpg](https://github.com/nomadics9/NixOS-Flake/assets/90281553/0e09d225-d097-45f7-a068-7efa45337d88)

The contents of `/boot/EFI` look like this.
![20230619_003314.jpg](https://github.com/nomadics9/NixOS-Flake/assets/90281553/070ce180-60b8-48a2-af21-44724ed1b32a)



sorry it's a picture not text

**Comment by RUNFUNRUN** [comment]
I changed the path to `/boot` and was able to install. However, after rebooting, I encountered a freeze at the login screen. I will try to find the cause by myself.

I will close this issue since the installation error issue has been resolved. Thank you very much.

**Comment by nomadics9** [comment]
just change to /boot/EFI then, paths in linux are case sensitive.

**Comment by nomadics9** [comment]
![image](https://github.com/nomadics9/NixOS-Flake/assets/60583633/fda991d8-a8b4-4827-917b-023222d17a47)

correct /boot should work for you. as I have my EFI and loader inside /boot/efi

for the frozen login screen, can you access tty. if you can login thru tty. then 
`Hyprland`
see if it works.

if not try to comment out nvidia module if you are not using nvidia in configuration.nix and install.

I'm glad I could help!

you can add me in discord to help you in installing 😃
nomadics

**Comment by RUNFUNRUN** [comment]
It was probably because I had auto-login turned on and my monitor settings in hyprland.  It's working fine now! Thank you! I sent you a friend request on discord!

![20230619_033024.jpg](https://github.com/nomadics9/NixOS-Flake/assets/90281553/161b6153-359a-416a-b48a-a93b5623fb39)

**Comment by FatngatirBilek** [comment]
@RUNFUNRUN how you make this works??I have the same issue

**Comment by RUNFUNRUN** [comment]
> @RUNFUNRUN how you make this works??I have the same issue

Hi, which do you have an error boot or hyprland?

**Comment by FatngatirBilek** [comment]
> > @RUNFUNRUN how you make this works??I have the same issue
> 
> Hi, which do you have an error boot or hyprland?

![IMG_20240227_054440~2](https://github.com/nomadics9/NixOS-Flake/assets/81058978/92d5d7b6-6da2-479a-843f-5d9b4f6f6c49)
this what i got now after fixed the boot thing

now in gnome login manager there is only Arabic keyboard layout 💀💀

**Comment by RUNFUNRUN** [comment]
I do not know about the keyboard layout issue. Sorry.

**Comment by FatngatirBilek** [comment]
> I do not know about the keyboard layout issue. Sorry.

nvm it works now.
btw i'm new to nix, how to add packages on the configuration file, do I have to edit the $home/NixOS-Flake/configuration.nix and run nixos-rebuild swith --flake .#username or can I edit in /etc/nixos/configuration.nix ?
